export const UNKNOWN = 'There was an unexpected error'
export const NOT_LOGGED_IN = 'You must be logged in'
export const NOT_FOUND = 'Not found'
export const INVALID = 'Invalid'
export const EXPIRED = 'Expired'
export const DUPLICATE = 'Duplicate'
export const UPLOAD_ERROR = 'Upload error'
export const HASH_ERROR = 'Hash error'
